---
# tasks file for ansible-role-sensu-server

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ sensu-server_log_dir }}"
    mode: 0755
    owner: "{{ sensu-server_user }}"
    group: "{{ sensu-server_group }}"
    state: directory
  notify: Restart sensu-server

- name: Create db directory
  file:
    path: "{{ sensu-server_db_dir }}"
    mode: 0755
    owner: "{{ sensu-server_user }}"
    group: "{{ sensu-server_group }}"
    state: directory
  notify: Restart sensu-server

- name: Create sensu-server.conf
  template:
    src: sensu-server.conf.j2
    dest: "{{ sensu-server_conf_file }}"
    validate: echo %s
  notify: Restart sensu-server

- name: Start sensu-server
  service:
    name: "{{ sensu-server_service }}"
    enabled: true
    state: started
