---
# tasks file for ansible-role-sensu-server

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create sensu_server_conf_d_dir
  file:
    path: "{{ sensu_server_conf_d_dir }}"
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    state: directory

- name: Create sensu_server_extensions_dir
  file:
    path: "{{ sensu_server_extensions_dir }}"
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    state: directory

- name: Create sensu_server_plugins_dir
  file:
    path: "{{ sensu_server_plugins_dir }}"
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    state: directory

- name: Create sensu_server_log_dir
  file:
    path: "{{ sensu_server_log_dir }}"
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    state: directory

- name: Create sensu_server_config_file
  template:
    src: config.json.j2
    dest: "{{ sensu_server_config_file }}"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  notify: Restart sensu-server

- name: Create json files
  template:
    src: json.j2
    dest: "{{ sensu_server_conf_d_dir }}/{{ item }}.json"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  with_items: "{{ sensu_server_config_fragments.keys() }}"
  notify: Restart sensu-server

- name: Start sensu-server
  service:
    name: "{{ sensu_server_service }}"
    enabled: true
    state: started
